version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace/frontend
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
volumes:
  node_modules:
