version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      sh -c "cd frontend && npm run dev & cd backend && flask run --host=0.0.0.0 --port=5001"
    ports:
      - "3000:3000"
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
volumes:
  node_modules:
